function bt_eval(k,n){try{return window.eval.apply(window,[k])}catch(u){n&&n(u)}}var bt_parameter=function(){var k;return function(n,u){var C=u||document;"undefined"===typeof k&&(k=new BrightTag.HTTP.URL(C.location.href));return k.param(n)}}();function bt_meta(k,n){for(var u,C=(n||document).getElementsByTagName("meta"),H=0,J=C.length;H<J;H++)if(u=C[H],u.getAttribute("name")===k)return u.getAttribute("content");return""}
function bt_cookie(k,n){return(new BrightTag.HTTP.Cookie(n||document)).get(k)||""}function bt_data(k,n){var u=BrightTag.V2_RESPONSE?BrightTag.configuredSites()[0]:BrightTag.instance;return u?u.data(k,n):""}window.bt_data_escaped=bt_data;function bt_log(k){window.console&&console.log&&console.log("Signal: "+k)}var bt_handle_exception=bt_log;
window.BrightTag=function(k){function n(a,d){return Object.prototype.toString.call(a)==="[object "+d+"]"}function u(a){return a.replace(/^\s\s*/,"").replace(/\s\s*$/,"")}function C(a){return"\n//at-sourceURL=/BrightTag/"+a.replace(/\s+/g,"_")+".js"}function H(a,d){for(var c=0,b=this.length;c<b;c++)a.call(d,this[c],c,this)}function J(a,d,c){for(var b in a)a.hasOwnProperty(b)&&d.call(c,b,a[b],a)}function r(a,d,c){a&&(O(a)?P.call(a,d,c):p.isObject(a)&&J(a,d,c))}function s(a,d){J(d,function(d,b){a[d]=
b});return a}function O(a){return p.isArray(a)||!p.isString(a)&&a.length}function pa(a){return!!a}function qa(a,d){var c=Array.isArray(this)?this.slice():Array.from(this),b=[];P.call(c,function(c,e){a.call(d,c,e,this)&&b.push(c)});return b}function U(a,d,c){if(a)return ra.call(O(a)?a:[a],d||pa,c)}function sa(a,d){var c=Array.isArray(this)?this.slice():Array.from(this),b=Array(c.length);P.call(c,function(c,e){b[e]=a.call(d,c,e,this)});return b}function A(a,d){var c,b,h=p.isArray(a)?a:[a];c=0;for(b=
h.length;c<b;c++)if(h[c]===d)return!0;return!1}function V(a){return!p.isString(a)?a:a.replace(/%/g,"%25").replace(/#/g,"%23").replace(/&/g,"%26").replace(/'/g,"%27").replace(/;/g,"%3B").replace(/</g,"%3C").replace(/>/g,"%3E")}function W(a){for(var d=5381,c=0,b=a.length;c<b;)d=(d<<5)+d+a.charCodeAt(c++);return d.toString(36)}function Q(a){if("s.yjtag.jp"===a&&"false"!==k.HTTP.Cookie(document).get("testyjproxy"))return"yjtag.yahoo.co.jp"}function X(a){function d(){}function c(a){var b=Array.prototype.slice.call(arguments,
1);x.each(r,function(g){var l=[t].concat(b);(g[a]||d).apply(null,l)})}function b(){D=!0;R=y.length;c("engine:off")}function h(){D&&c("engine:on");D=!1;Y=0;(y[R++]||b)()}function e(a,b){return{type:a,exception:b}}function f(){c("block:finish");h()}function m(b,g){var l=a.createElement(b.tagName),c=x.extend(x.extend({},b.defaults),g||{});x.each(b.supported,function(a){p.isString(a)&&null!=c[a]?l[a]=c[a]:p.isObject(a)&&null!=c[a.option]&&a.setter(l,c[a.option])});return l}function l(b,g){var l=m(s.iframe,
g);l.onerror=function(){c("block:error",e("iframe","Problem loading "+b))};c("block:start",b);l.src=b.toString();a.body.appendChild(l);f()}function g(a,b){var l=m(s.image,b);l.onerror=function(){c("block:error",e("image","Problem loading "+a))};c("block:start",a);l.src=a.toString();f()}function v(b,l,g){var d=!1,v=m(s.script,g);v.onerror=function(){c("block:error",e("script","Problem loading "+b));d||f()};v.onload=v.onreadystatechange=function(){var a;if(!(a=d)){a:{switch(v.readyState){case void 0:case "loaded":case "complete":a=
!0;break a}a=!1}a=!a}a||(d=!0,f())};c("block:start",b);b&&(v.src=b.toString());l&&(v.text=l);l=a.getElementsByTagName("script")[0];l.parentNode.insertBefore(v,l)}function q(a){var b=Array.prototype.slice.call(arguments,1);return function(){a.apply(null,b)}}function K(b){return function(){try{if(c("block:start",b),p.isString(b)){var l=x.trim(b).replace(/^\x3c!--/,"").replace(/--\x3e$/,"");a.defaultView?a.defaultView.eval.call(window,l):a.parentWindow?a.parentWindow.execScript(l):c("block:error",e("wait",
"Could not evaluate wait block ["+l+"]"))}else b()}catch(g){c("block:error",e("wait",g))}finally{f()}}}function w(a){y.push(a);D&&h();return t}function k(a){y.splice(R+Y++,0,a);return t}var t=this,r=[],B={},D=!1,y=[],R=0,Y=0,s={iframe:{tagName:"iframe",defaults:{frameborder:"0",height:"1px",scrolling:"no",width:"1px"},supported:[{option:"display",setter:function(a,b){a.style.display=b}},"frameborder","id","height","scrolling","width"]},image:{tagName:"img",defaults:{},supported:[{option:"display",
setter:function(a,b){a.style.display=b}},"id",{option:"height",setter:function(a,b){a.setAttribute("height",b)}},{option:"width",setter:function(a,b){a.setAttribute("width",b)}}]},script:{tagName:"script",defaults:{type:"text/javascript"},supported:["async","id","type","charset"]}};t.run=function(){c("engine:on");h()};t.options=function(a){x.extend(B,a);return t};t.option=function(a){return B[a]};t.iframe=function(a,b){return w(q(l,a,b))};t.image=function(a,b){return w(q(g,a,b))};t.script=function(a,
b,l){return w(q(v,a,b,l))};t.wait=function(a){return w(K(a))};t.preemptCss=function(a,b){return k(q(v,a,b))};t.preemptIframe=function(a,b){return k(q(v,a,b))};t.preemptImage=function(a,b){return k(q(v,a,b))};t.preemptScript=function(a,b,l){return k(q(v,a,b,l))};t.preemptWait=function(a){return k(K(a))};t.listen=function(a){r.push(a);(a["engine:listen"]||d).apply(null,[t]);return t}}function Z(a){function d(a){e.push(a);m&&!l&&b()}function c(a){a.run()}function b(){var a=e[f];a&&(f++,a.listen(g).run())}
var h,e=[],f=0,m=!1,l=!1,g={"engine:on":function(){l=!0},"engine:off":function(){l=!1;b()}};h=d;this.alwaysQueue=function(){h=d};this.neverQueue=function(){h=c};this.push=function(a){h(a);return a};this.run=function(){m=!0;b()};this.applyListener=function(a){var b,l;b=f;for(l=e.length;b<l;b++)e[b].listen(a)};this.toString=function(){return"Group[name="+a+"; working="+l+"; running="+m+"]"}}function $(a,d){return{"engine:listen":function(c){c.listen(new ta(a,d))}}}function aa(a){function d(a){return h[a]||
(h[a]=new Z(a))}function c(a){return b.addToGroup(a,b.newEngine())}var b=this,h={undefined:new Z(void 0)},e=[];h.undefined.neverQueue();b.addGlobalListener=function(a){e.push(a);r(h,function(b,l){l.applyListener(a)})};b.addToGroup=function(a,b){r(e,function(a){b.listen(a)});return d(a).push(b)};b.newEngine=function(){return new X(a)};b.group=function(a){return c(a)};b.listen=function(){return c().listen.apply(null,arguments)};b.iframe=function(){return c().iframe.apply(null,arguments)};b.image=function(){return c().image.apply(null,
arguments)};b.script=function(){return c().script.apply(null,arguments)};b.wait=function(){return c().wait.apply(null,arguments)};b.run=function(a){d(a).run()};b.alwaysQueue=function(a){d(a).alwaysQueue()};b.neverQueue=function(a){d(a).neverQueue()};b.setOptions=function(){return c()}}function S(a){function d(a){var b,c=a.split(m),d;h={};a=0;for(b=c.length;a<b;a++)(d=f.exec(c[a]))&&(h[d[1]]=unescape(d[2]))}function c(b,g,c){if(b){c=c||{};b=[b+"="+V(g||"")];if((g=c.expires)||0===g)p.isNumber(g)&&(g=
(new Date(g)).toGMTString()),b.push("expires="+g);(g=c.path)&&b.push("path="+g);(g=c.domain)&&b.push("domain="+g);b.push("Secure");!0===c.httponly&&b.push("HttpOnly");b.push("SameSite=None");c=b.join(";");if(c.length<e)a.cookie=c;else throw{name:"CookieTooLongError",message:"Cookie reached 4096 byte limit"};d(a.cookie)}}function b(a,b){c(a,"",s(b||{},{expires:1}))}var h={},e=4096,f=/([^=]+)=?(.*)/,m=/; ?/;d(a.cookie||"");return{get:function(a){return h[a]},set:c,remove:b,findEach:function(a,b){for(var c in h)h.hasOwnProperty(c)&&
c.match(a)&&b(c,h[c])},clear:function(a){var c=s({},h),d;for(d in c)b(d,a)}}}function ba(a){a=S(a);var d=a.set,c=a.remove;a.set=function(a,c,e){e=s(e||{},{path:"/"});0===e.expires&&(e.expires=+new Date("1/1/2038"));d(a,c,e)};a.remove=function(a,d){c(a,s(d||{},{path:"/"}))};a.purge=function(){};return a}function ca(a,d){function c(a){a=a.expires;return 0!==a&&a<=+new Date}function b(b,c){a.setItem(b,c)}function h(a,b,e){b={value:b,expires:e};c(b)||d.setItem(a,JSON.stringify(b))}function e(a){a=d.getItem(a);
try{return a?JSON.parse(a):void 0}catch(b){}}function f(a){a=e(a);var b;return a&&(a.hasOwnProperty("value")&&a.hasOwnProperty("expires"))&&!c(a)?(b=a.value,delete a.value,[b,a]):[]}function m(a,b,c,d){for(var e,m=0,f=a.length;m<f;m++)e=a.key(m),!c[e]&&(c[e]=e.match(b))&&d(e)}return{set:function(a,c,d){a&&null!=c&&(d=d||{},(null!=d.expires?h:b)(a,c,d.expires))},get:function(b){return a.getItem(b)||f(b)[0]},findEach:function(b,c){var e={};m(a,b,e,function(b){var d=a.getItem(b);null!=d&&c(b,d)});m(d,
b,e,function(a){var b=f(a),d=b[0],b=b[1];null!=d&&c(a,d,b)})},remove:function(b){a.removeItem(b);d.removeItem(b)},purge:function(){for(var a,b,m=d.length;m--;)a=d.key(m),(b=e(a))&&(b.hasOwnProperty("value")&&b.hasOwnProperty("expires"))&&c(b)&&d.removeItem(a)}}}function L(a,d){var c={};c.set=a.set;c.findEach=function(b,c){var e={};a.findEach(b,function(a,b,d){e[a]=!0;c(a,b,d)});d.findEach(b,function(b,d,l){e[b]||(a.set(b,d,l),c(b,d,l))})};c.get=function(b){var c=a.get(b);void 0===c&&(c=d.get(b),void 0!==
c&&a.set(b,c));return c};c.remove=function(b){a.remove(b);d.remove(b)};c.purge=function(){a.purge();d.purge()};return c}function M(a){function d(a){var b={};if(!p.isString(a))return a;r(a.split("&"),function(a){if(""!==a){var c=a.split("=");a=decodeURIComponent(c[0]);c=c[1]&&decodeURIComponent(c[1].replace(/\+/g," "));(null==b[a]?b[a]=[]:b[a]).push(c)}});return b}function c(a,b){var c=[];r(a,function(a){if(p.isObject(a))return!1;a=null==a||""===a?b:a;(p.isString(a)||p.isNumber(a)||p.isBoolean(a))&&
c.push(a)});return c}function b(a){return!p.isArray(a)?[a]:a}function h(a,b){var c=encodeURIComponent(a),d=encodeURIComponent(b);return c+"="+d}var e=this,f={};s(f,d(a));e.param=function(a){a=f[a]||[""];return 1<a.length?a:a[0]};e.params=function(){return f};e.appendParam=function(a,d){if(a){var e=c(b(d));0<e.length&&(f[a]=(null==f[a]?f[a]=[]:f[a]).concat(e))}return this};e.replaceParam=function(a,d){if(a){var e=c(b(d));0<e.length&&(f[a]=(f[a]=[]).concat(e))}return this};e.appendParams=function(a){r(a,
e.appendParam);return this};e.alwaysAppendParam=function(a,d){if(a){var e=c(b(d),"");0<e.length&&(f[a]=(null==f[a]?f[a]=[]:f[a]).concat(e))}return this};e.alwaysReplaceParam=function(a,d){if(a){var e=c(b(d),"");0<e.length&&(f[a]=(f[a]=[]).concat(e))}return this};e.alwaysAppendParams=function(a){r(a,e.alwaysAppendParam);return this};e.appendPartialQueryString=function(a){a&&e.alwaysAppendParams(d(a));return this};e.deleteParam=function(a){delete f[a]};e.toString=function(){var a=[];r(f,function(b,
c){r(c,function(c){a.push(h(b,c))})});return a.join("&")}}function E(a){function d(){var a=k.toString();return f+m+(0<a.length?"?"+a:"")}var c={},b,h,e,f,m,l,g,v,q,k,w=a.match(ua);a=w[1]||"";h=w[2]||"";e=(w[3]||"").substring(1);b=h+(e?":"+e:"");f=a+(b?"//"+b:"");m=w[4]||"";l=(g=m.match(/^(.+?)?\/([^\/]+)?$/))&&g[1]||"";g=g&&g[2]||"";v=(w[5]||"").substring(1);q=(w[6]||"").substring(1);k=new M(v);s(c,k);s(c,{origin:f,scheme:a,host:b,hostname:h,port:e,path:m,pathname:l,scriptname:g,queryString:k.toString,
fragment:function(){return q},tooLong:function(){return 2082<d().length},asString:d});c.toString=d;return c}function da(a,d,c){function b(){var b=c.createEvent("Event");b.initEvent(d,!0,!1);try{b.currentTarget=b.target=a}catch(e){bt_log("warning: can not set target for ["+d+"] event: "+e)}return b}function h(){var a=c.createEventObject("Event");a.type=d;a.cancelable=!0;a.bubbleable=!1;return a}function e(c){setTimeout(function(){try{(c.handleEvent||c).call(a,f?b():h())}catch(e){bt_log("error: overriding ["+
d+"] event: "+e)}},0)}var f=!!a.addEventListener,m=f?"addEventListener":"attachEvent",l=a[m];a[m]=function(b,c,h){if(c&&("function"==typeof c||"function"==typeof c.handleEvent))if(b==d||b=="on"+d)e(c);else try{f?l.call(a,b,c,h):l(b,c)}catch(m){bt_log("error: proxying ["+b+"] event: "+m)}}}function ea(a,d,c){function b(a){a.hasOwnProperty("enabled")&&(v=a.enabled);a.hasOwnProperty("timestamp")&&(k=a.timestamp,v=!0);a.hasOwnProperty("site")&&(l=a.site);a.hasOwnProperty("referrer")&&(g=a.referrer)}function h(c){c&&
b(c);q=[];a.remove(d)}function e(){try{return JSON.stringify({site:l,referrer:g,errors:q})}catch(a){bt_log("problem serializing errors: "+a.message)}return null}function f(a){var b=p.isObject(a)?s({},a):{};b.type=b.type||"unknown";b.message=b.message||a.toString();b.timestamp=k;return b}function m(){h();q.push(f({type:"runtime",message:"Too many errors"}));a.set(d,e())}if(!a)throw Error("ErrorManager requires a store");var l,g,v=!0,q=[],k=+new Date;c&&b(c);return{configure:b,reset:h,hasErrors:function(){return 0<
q.length},tooManyErrors:m,processStoredErrors:function(){var b=a.get(d);if(b)try{var c=JSON.parse(b)||{};l=c.site;g=c.referrer;p.isArray(c.errors)&&(q=q.concat(c.errors))}catch(e){bt_log("problem reading stored errors: "+e.message)}},push:function(b){bt_log("error: "+JSON.stringify(b));if(v&&b&&!(-1>b.tagId||-1>b.pageId))try{q.push(f(b)),a.set(d,e())}catch(c){if("CookieTooLongError"!=c.name)throw c;m()}},toJSON:e,toArray:function(){return q}}}function fa(a,d){return new function(a,b){function d(a){g.wait(a)}
function e(a){function b(){l=k.jQuery;d(a)}m="var $ = BrightTag.$; ";k.jQuery?b():g.script(k.instance.baseUri()+"BrightTag.jquery-1.5.1.js").wait(b)}var f={},m="",l,g=k.Blab.group(b);f.getJQuery=function(){return l};f.ensureJQuery=function(m){f.ensureJQuery=d;l=a.jQuery;(l?d:e)(m);k.Blab.run(b)};f.functionWithAccess=function(a,b){return new Function(a,m+b)};return f}(a,d)}function ga(a){function d(a,c){c&&c.findEach(a,function(a,c){b.appendParam(a,c)})}function c(a,b){return function(c){bt_log("invalid "+
a+" expression: "+b+", exception = "+c)}}var b=this,h=a.window,e=a.parentReferrer,f=a.referrer,m=E(0===a.host.length?"":(/^[a-z0-9+.-]+:\/\/.+/.test(a.host)?"":"//")+a.host+"/tag"),l=a.store?a.store.get("X-BT-InspectSession"):null;s(b,m);b.toString=m.toString;b.appendParams({site:a.site,referrer:f,docReferrer:a.docReferrer,mode:a.mode,H:W(f||a.document.location.href)});l&&b.appendParam("inspect-session",l);f!==e&&b.appendParam("parentReferrer",e);a.gdpr_consent&&b.appendParams({gdpr_consent:a.gdpr_consent});
a.gdpr&&b.appendParams({gdpr:a.gdpr});d(/^btps\..+/,new S(a.document));d(/^btpdb\..+/,a.store);b.appendData=function(a){var c=bt_data(a),c=p.isArray(c)||p.isObject(c)?h.JSON.stringify(c):c;return b.alwaysReplaceParam("_cb_"+("bt_data('"+a+"')"),c)};b.appendJs=function(a){var d=c("client binding expression",a);return b.alwaysReplaceParam("_cb_"+a,z(a,d))};b.cf=function(a){p.isArray(a)||(a=[a]);var c=b.param("cf");c&&(a=Array(c).concat(a));b.replaceParam("cf",a.join());return b};b.addCf=function(a,
d){if(!z(d,c("conditional fire",d,"tags/"+a+"-cf.js")))return!1;var e=b.param("cf");b.replaceParam("cf",e?e+","+a:a);return!0};b.length=function(){return b.toString().length};b.isTooLarge=function(){return 2028<b.length()};var g=b.toString();b.hasConditions=function(){return g!=b.toString()}}function ha(a,d){function c(a,b){r(b,function(b,c){a[a.type+"."+b]=c});d.push(a)}function b(a,b,c){var d=k.instance.serverURL();r(a,function(a){a.trigger(b,c,d)});d.hasConditions()&&(d.appendParam("mode","v1"),
k.Blab.script(d.asString()))}function h(a,d,e){function f(b,d){r(h,function(f){var g,m=f.name;try{g=k[f.dbe];if(!g){var h=k,q=f.dbe,w,p=f.dbe,t=C("event-dbes/"+m+"-page-"+(B||"adhoc")+"-event-"+a);w=l.functionWithAccess(["eventObject","eventData"],"return "+p+";"+t);g=h[q]=w}e.data(m,g.call(b.target,b,d))}catch(r){c({type:"evdbe",message:r.toString(),pageId:B||-1},{name:m,eventName:a})}})}var g={},h=[],k={},B=(d||{}).pageId;g.data=function(a,b){h.push({name:a,dbe:b});return g};g.applyDataBindings=
f;g.handler=function(c){var d,e=m[a];e&&0<e.length&&(d=Array.prototype.slice.call(arguments,1),f(c,d),b(e,c,d))};return g}function e(a){function b(a){0<h.length&&(a.cf(h),r(k,function(b){a.appendData(b)}),r(y,function(b){a.appendJs(b)}))}function d(a,b){return function(c){bt_log("Invalid "+a+" expression: "+b+", exception = "+c)}}var e={},f={},g,m,h=[],k=[],y=[];e.execute=function(b,d){s(f,d||{});if(p.isFunction(b))m=b;else if(p.isString(b))a:{try{var g=C("events/"+a+"-tag-"+(f.tagId||"adhoc"));m=
l.functionWithAccess(["eventObject","eventData"],b+g);break a}catch(h){c({type:"evparse",message:h.toString(),tagId:f.tagId||-1},{eventName:a})}m=void 0}else bt_log("when.execute: unknown action: "+b);return e};e.evaluate=function(a){g=a;return e};e.fire=function(a){h.push(a);return e};e.appendData=function(a){k.push(a);return e};e.appendJs=function(a){y.push(a);return e};e.trigger=function(e,h,l){var k=d("post-event conditional fire",g);if(!g||z(g,k)){try{m&&m.call(e.target,e,h)}catch(y){c({type:"evwait",
message:y.toString(),tagId:f.tagId||-1},{eventName:a})}b(l)}};return e}var f={},m={},l=fa(a,"BrightTag.jQuery"),g=/^direct\//i;f.executeActions=b;f.Binder=h;f.bind=function(a,b,c,d){var e=h(a,d,k.instance);l.ensureJQuery(function(){var a=l.getJQuery(),d=a(b);if(p.isString(b)&&!g.test(c)&&(d.on||d.live))if(d.on)a(document).on(c,b,e.handler);else d.live(c,e.handler);else d.bind(c.split(g).pop(),e.handler)});return e};f.EventAction=e;f.when=function(a){var b=e(a),c=m[a];c||(c=m[a]=[]);c.push(b);return b};
return f}function va(a,d,c,b){function h(b,d,e){var f=a.group(e).options(d||{});f.wait(function(){c.process(f,b)})}var e=!1,f={};f[b]=!0;return{tag:function(c,d){var g;g=d&&d.group;g=!e&&!g?b:g;h(c,d,g);g&&void 0===f[g]&&(f[g]=!0,e&&a.run(g))},run:function(){a.addGlobalListener($(d,c));e=!0;r(f,a.run)}}}function ia(a,d){function c(a){r(p.isArray(a)?a:[a],function(a){p.isFunction(a)?a():q.write('<script type="text/javascript" src="'+a+'">\x3c/script>')})}function b(a){var b=w.group().options({tagId:-2});
r(p.isArray(a)?a:[a],function(a){(p.isFunction(a)?b.wait:b.script)(a)})}function h(a){q.write(a)}function e(a,b){B.tag(a,b)}function f(a){g.writeScript=a?c:b;g.appendContent=a?h:e}function m(a){r(a,function(a){if(a.name){var b=s({},a);delete b.name;delete b.value;t.set(a.name,a.value,b)}})}function l(b){n.hasErrors()&&(b.appendParam("errors",n.toJSON()),b.tooLong()&&(b.deleteParam("errors"),n.tooManyErrors(),b.appendParam("errors",n.toJSON())));n.reset({site:a.site,referrer:a.referrer||q.location.href})}
var g=this,v=a.data||{},q=a.document||{},K=a.window||{},w=a.blab||k.Blab,n=a.errorManager,t=a.store,u=ja(q),B=a.asyncTagManager||va(w,q,u,"domready"),D=fa(window,"jquery");g.referrer=a.referrer;g.parentReferrer=a.parentReferrer;g.docReferrer=a.docReferrer;g.site=a.site;g.host=a.host;g.gdpr_consent=a.gdpr_consent;g.gdpr=a.gdpr;g.loadOnly=!!a.loadOnly;n&&w.addGlobalListener(new ka(n));w.run("serializer");g.load=function(){var a=Array.prototype.slice.call(arguments,0);r(a,function(a){p.isFunction(a)?
w.addToGroup("serializer",w.newEngine().wait(function(){a(g)})):p.isObject(a)&&a.src?g.library(a.src,a.options):p.isString(a)&&g.library(a)})};g.library=function(a,b){w.addToGroup("serializer",w.newEngine().options(b||{}).script(a))};f(A(a.mode,"sync"));g.domReady=function(){A(a.mode,"sync")&&f(!1);B.run()};g.parameter=function(a){return window.bt_parameter(a,q)};g.meta=function(a){return window.bt_meta(a,q)};g.cookie=function(a){return window.bt_cookie(a,q)};g.data=function(a,b){if(void 0!==b)return v[a]=
b;b=v[a];return null==b?"":b};g.dbe=function(a,b,c){function d(b){n&&n.push({type:"dbe",message:b.toString(),"dbe.name":a,pageId:(c||{}).pageId||-1})}null==v[a]&&g.data(a,z(b,d,"page-dbes/"+a+"-page-"+(c&&c.pageId||"adhoc")))};g.errors=function(a){k.V2_RESPONSE=!1;n.configure(a)};g.store=t?m:function(){};g.serverURL=function(){return new ga(a)};g.defaultBaseUri=function(){return("https:"==q.location.protocol?"https:":"http:")+"//s.btstatic.com/"};g.baseUri=function(){var a=/\btag(\-\d+\.\d+\.\d+|\.[^.]+|-n)?\.js(#.*)?$/;
return d&&d.src&&d.src.replace(a,"")||g.defaultBaseUri()};g.primary=function(){function a(){var b=g.serverURL();n&&(n.processStoredErrors(),l(b));return b.toString()}var b=[];K.JSON?b.push(a()):(b.push(g.baseUri()+"json2.js"),b.push(function(){g.writeScript(a())}));g.writeScript(b)};g.secondary=function(a){var b=g.serverURL(),c=b.toString();a(b);b.toString()!=c&&(b.appendParam("mode","v1"),n&&l(b),b.isTooLarge()?g.post(b):g.writeScript(b.toString()))};g.post=function(a){D.ensureJQuery(function(){D.getJQuery().ajax({url:"//"+
a.host+a.path,type:"POST",dataType:"text",success:bt_eval,data:a.queryString(),xhrFields:{withCredentials:!0}})})}}function F(){var a={},d={};return{on:function(c,b){var d=a[c];d||(d=a[c]=[]);d.push(b)},once:function(a,b){var h=d[a];h||(h=d[a]=[]);h.push(b)},emit:function(c){function b(a){a.apply(this,h)}var h=Array.prototype.slice.call(arguments,1);r(a[c],b);r(d[c],b);d[c]=[]}}}function wa(a){function d(a){return null!=h[a]}function c(a,b){void 0!==b&&(h[a]=b);var c=h[a];return null==c?"":c}var b,
h=s({},a);return b=s({dbe:function(a,f,h){if(!d(a)&&(f=z(f,function(c){b.emit("error",c,a,h)}),null!=f))return c(a,f)},data:c,hasData:d},F())}function xa(a){var d,c={},b=["eventObject","eventData","$","bt_data"];return d=s({dbe:function(a,e){try{c[a]=new Function(b,"return "+e+";")}catch(f){f.type="evdbe",d.emit("error",f,a)}return d},trigger:function(b,e,f){var m=b.target,l=[b,e,f,a.data];r(c,function(b,c){try{a.data(b,c.apply(m,l))}catch(e){e.type="evdbe",d.emit("error",e,b)}})}},F())}function ya(a){function d(a){h.push(a);
return b}function c(a){try{return new Function(f,a)}catch(c){c.type="evparse",b.emit("error",c)}}var b,h=[],e=function(){return!0},f=["eventObject","eventData","$","bt_data"];return b=s({fire:function(a){return d(function(b){b.fire(a)})},appendData:function(a){return d(function(b){b.appendData(a)})},appendJs:function(a){return d(function(b){b.appendJs(a)})},execute:function(e){function f(c,d,e,h){try{g.call(d.target,d,e,h,a.data)}catch(m){m.type="evwait",b.emit("error",m)}}var g=p.isString(e)?c(e):
e;return g?d(f):b},evaluate:function(d){var f=c("return "+d);e=f?function(b,c,d,e){return f.call(c.target,c,d,e,a.data)}:function(){return!1};return b},trigger:function(a,b,c,d){e(a,b,c,d)&&r(h,function(e){e(a,b,c,d)})}},F())}function za(a){var d=/^direct\//i,c=!1;return{bind:function(a,c,e){function f(a){var b=Array.prototype.slice.call(arguments,1);e(a,b,k.jQuery||window.jQuery)}var m=k.jQuery||window.jQuery,l=m(a),g=!p.isString(a)||d.test(c);if(!g&&l.on)m(document).on(c,a,f);else!g&&l.live?l.live(c,
f):l.bind(c.split(d).pop(),f)},newBinder:function(a){return xa(a)},newHandler:function(a){return ya(a)},ensureLibrary:function(b){k.jQuery||window.jQuery?b():(c||(c=!0,a.run()),a.wait(b))}}}function Aa(a,d){function c(b,c,d,l){var g=T(a);r(b,function(a){a.trigger(g,c,d,l)});h.emit("triggered",g)}var b={},h=F();return s(h,{bind:function(e,f,m,l){function g(a,d,f){k.trigger(a,d,f);c(b[e],a,d,f)}var k=d.newBinder(a,e);k.on("error",function(a,b){h.emit("error",a,{name:b,eventName:e},l)});d.ensureLibrary(function(){try{d.bind(f,
m,g)}catch(a){h.emit("error",a,{eventName:e},l)}});return k},handle:function(c,f){var m=d.newHandler(a);m.on("error",function(a){h.emit("error",a,{eventName:c},f)});b[c]=b[c]||[];b[c].push(m);return m}})}function ja(a){function d(a,b){a.src?b.preemptScript(a.src,a.innerHTML):a.innerHTML&&b.preemptWait(a.innerHTML)}function c(a,b){for(var f=a.childNodes||[],m=0,l=f.length;m<l;m++){var g=f[m];"SCRIPT"==g.tagName?d(g,b):c(g,b)}}var b=a.createElement("div");return{process:function(h,e){if(0!==e.length){b.innerHTML=
"<br/>"+e;for(var f=b.childNodes||[],m=1,l=f.length;m<l;m++){var g=f[m];if("SCRIPT"==g.tagName)d(g,h);else{try{a.body.appendChild(g.cloneNode(!0))}catch(k){bt_log("error appending content to body: "+k)}c(g,h)}}}}}}function Ba(a){function d(b){a.write(b);return c}var c={tag:d,script:function(a){return d('<script type="text/javascript" src="'+a+'">\x3c/script>')},wait:function(a){a();return c}};return c}function Ca(a,d){function c(c,d){var h=c&&c.group;d(a.group(h).options(c||{}));h&&void 0===b[h]&&
(b[h]=!0,a.run(h))}var b={},h={tag:function(a,b){c(b,function(b){b.wait(function(){d.process(b,a)})});return h},script:a.script,wait:a.wait};return h}function Da(a,d){var c=d;return{tag:function(a,d){return c.tag(a,d)},script:function(a){return c.script(a)},wait:function(a){return c.wait(a)},sync:function(){c=a},async:function(){c=d}}}function ka(a){return{dbe:function(d,c,b){a.push({type:"dbe",message:d.toString(),"dbe.name":c,pageId:(b||{}).pageId||-1})},events:function(d,c,b){var h=d.type,e="evdbe"===
h?"pageId":"tagId",f={type:h,message:d.toString()};r(c,function(a,b){f[h+"."+a]=b});f[e]=(b||{})[e]||-1;a.push(f)},"block:error":function(d,c){var b,h,e;c&&(b=c.type,h=c.exception||c,e=d.option("tagId")||-1,a.push({type:b,message:h.toString(),tagId:e}))}}}function Ea(a){function d(){var b=new E(a.src),c={},d=b.fragment(),f=Q(b.host);c.staticHost=b.host+b.pathname;f&&(c.host=f);d&&r((new M(d)).params(),function(a,b){c[a]=1<b.length?b:b[0]});return c}function c(){var b=u(a.innerHTML);return 0===b.length?
{}:z("(\n"+b+"\n)",function(a){bt_log("json configuration error: "+a)})}return{isTagjs:function(){return/\/tag(\-\d+\.\d+\.\d+|\.[^.]+|-n)?\.js(\?.*)?(#.*)?$/.test(a.src)},toJSON:function(){return s(d(),c())},script:a}}function Fa(a){return{isTagjs:function(){return!0},toJSON:function(){return a||{}},script:{src:void 0}}}function la(){function a(){return d}var d;return d={fire:a,appendData:a,appendJs:a,execute:a,when:a}}function T(a){function d(a,b){for(var c in a)if(b(c,a[c]))return!0;return!1}var c,
b=[],h={};return c={toJSON:function(){var a=0<b.length?{cf:b.join()}:{};return s(a,h)},fire:function(a){p.isArray(a)||(a=[a]);a=U(a,function(a){return null!=a&&""!==a});b=b.concat(a);return c},appendData:function(b){var d=a.data(b);h["_cb_bt_data('"+b+"')"]=p.isArray(d)||p.isObject(d)?JSON.stringify(d):d;return c},appendJs:function(a){h["_cb_"+a]=z(a);return c},execute:function(a){a();return c},when:function(b){var d;try{return d=new Function(["bt_data"],"return "+k.trim(b)),d(a.data)?c:la()}catch(h){bt_log("conditional evaluation error: ["+
h.toString()+"] while evaluating ["+b+"]")}return la()},hasConditions:function(){return 0<b.length||d(h,function(a,b){return null!=b})}}}function Ga(a,d,c,b,h,e){function f(){t=!0;d.async();n.mode=x.filter(n.mode,function(a){return"sync"!==a})}function m(a){if(null==a||a.hasConditions())b.reset({site:n.site,referrer:n.referrer||window.location.href})}function l(a){var c=E("//"+r+"/tag").appendParams({site:n.site,mode:n.mode,H:n.H,referrer:n.referrer,docReferrer:n.docReferrer}).appendParam("mode",
"v2").alwaysAppendParams(a);a=I.get("X-BT-InspectSession");var d=n.gdpr_consent,e=n.gdpr;a&&c.appendParam("inspect-session",a);h.findEach(RegExp("^btp(s|db)\\."+n.site+"\\..+"),function(a,b){c.appendParam(a,b)});d&&c.appendParams({gdpr_consent:d});e&&c.appendParams({gdpr:e});return c.appendParams({errors:b.hasErrors()?b.toJSON():null})}function g(a){if(null==a)return l();if(a.hasConditions())return l(a.toJSON())}function p(a){var b=g(a);b?(m(a),b.tooLong()?u.ensure("jQuery",function(){k.jQuery.ajax({url:b.origin+
b.path,type:"POST",data:b.queryString(),xhrFields:{withCredentials:!0}})}):d.script(b.toString())):m(a)}var q,n=x.extend({},e),r=n.host||"",s=F(),t=!1,u=new Ha(d,n);c.on("triggered",p);return q=x.extend({config:n,diagnostic:function(a){a&&(n.diagnostic=a,q.emit("diagnostic",a))},errors:function(a){b.configure({timestamp:a})},dbe:function(b,c,d){var e=a.dbe(b,c,d);null!=e&&q.emit("dbe",b,c,e,d)},data:a.data,dataref:function(a){return null==a?"":'BrightTag.site("'+n.site+'").data("'+a.replace(/"/g,
"\\x22")+'")'},store:function(a){x.each(a,function(a){if(a.name){var b=x.extend({},a);delete b.name;delete b.value;h.set(a.name,a.value,b)}})},tag:function(a,b){q.emit("tag",a,b);return d.tag(a,b)},script:d.script,wait:d.wait,events:{bind:function(a,b,d,e){q.emit("event-binding",a,b,d,e);return c.bind(a,b,d,e)},on:c.handle},when:function(b,c){T(a).when(b).execute(function(){c(q)});return q},domready:function(a){if(null==a)f();else s.once("domready",a);t&&s.emit("domready",q)},primary:function(){u.ensure("JSON",
function(){b.processStoredErrors();p()})},secondary:function(b){var c=T(a);b(c);p(c)}},F())}function Ia(a){a=E(a.staticHost+"/BrightTag.jquery-1.5.1.js");return za((new X(document)).script(a))}function Ja(a,d,c){var b=Ba(document);a=Ca(a,d);b=Da(b,a);x.contains(c.mode,"sync")&&b.sync();return b}function Ka(a){var d,c,b,h,e,f,m,l;if((m=a.site)&&!N[m])return d=wa(a.data),c=new aa(document),l=ja(document),b=Ja(c,l,a),e=Aa(d,Ia(a)),f=ea(G?L(G,I):I,"__bterr_"+m,{site:m,referrer:a.referrer,enabled:!1}),
h=ka(f),d.on("error",h.dbe),e.on("error",h.events),c.addGlobalListener(h),k.Events.onDOMReady(function(){c.addGlobalListener($(document,l))}),a=N[m]=Ga(d,b,e,f,G?L(I,G):I,a)}function ma(a,d,c){try{var b,h,e=a.toJSON();if(!(k.instance&&k.instance.site===e.site)){var f=e.referrer||d.location.href,m=s({host:"s.thebrighttag.com",staticHost:"s.btstatic.com",H:W(f),referrer:f.split("#")[0],docReferrer:d.document.referrer},e);b=Ka(m);if(e.site&&!k.instance&&!na&&!A(e.mode,"v2")&&!A(e.mode,"v2b")){var l=
a.script,g=oa();k.EventBinding=ha(g.window,g.errorManager);k.instance=new ia(s(g,e),l);h=k.instance;b.config.loadOnly=!0}else if(b){var n=b.config,q;var p=b.config.mode;q=A(p,"v2")?p:!p?"v2":["v2"].concat(p);n.mode=q}c&&c(b,h);return b}}catch(r){bt_log("error configuring site ["+a.script.src+"]: "+r)}}function La(a){var d,c,b=[];if(p.isArray(a))b=a.slice(0);else{d=0;for(c=a.length;d<c;d++)b.push(a[d])}return b}function Ma(a){if(!na&&!A(a.config.mode,"v2")&&!A(a.config.mode,"v2b"))k.Events.onDOMReady(function(d){a.domready()});
else a.config.loadOnly||(k.Events.onDOMReady(function(d){a.domready()}),a.primary())}function oa(){var a,d=ba(document),c=d,b=d;try{window.localStorage&&window.sessionStorage&&(a=ca(sessionStorage,localStorage),a.purge(),c=L(d,a),b=L(a,d))}catch(h){bt_log("Unable to access DOM storage: "+h)}return{id:Math.random(),loadOnly:!1,window:window,document:document,host:"s.thebrighttag.com",parentReferrer:top!=self&&self.window?self.window.location.href:null,docReferrer:document.referrer,data:{},store:c,
errorManager:ea(b,"__bterr")}}if(k)return k;var na=!1;k={};var p={isString:function(a){return n(a,"String")},isArray:function(a){return n(a,"Array")},isNumber:function(a){return n(a,"Number")},isBoolean:function(a){return n(a,"Boolean")},isFunction:function(a){return n(a,"Function")},isObject:function(a){return null===a||void 0===a?!1:n(a,"Object")}},z=bt_eval,P=Array.prototype.forEach?Array.prototype.forEach:H,ra=Array.prototype.filter?Array.prototype.filter:qa,Na=Array.prototype.map?Array.prototype.map:
sa,x={contains:A,each:r,extend:s,filter:U,map:function(a,d,c){if(a)return Na.call(O(a)?a:[a],d,c)},trim:u,getTagserveHostOverride:Q},ta=function(){function a(){}function d(a,b,c){try{a[b]=c}catch(d){bt_log("warning: could not assign value to 'document."+b+"': "+d)}}var c,b=[],h=function(a){c.push(a)};return function(e,f){var m;this["block:start"]=function(){b.push([c,e.write,e.writeln,e.open,e.close]);c=[];d(e,"write",h);d(e,"writeln",h);d(e,"open",a);d(e,"close",a)};this["block:finish"]=function(){try{f.process(m,
c.join(""))}finally{var a=b.pop();c=a[0];d(e,"write",a[1]);d(e,"writeln",a[2]);d(e,"open",a[3]);d(e,"close",a[4])}};this["engine:listen"]=function(a){m=a}}}(),ua=/^(?:([^:\/]+:)?\/\/)?([^:\/?#]+)?(:[0-9]+)?([^?#]*)(\?[^#]*)?(#.*)?$/,Ha=function(){function a(a,b){this.tagMgrRouter=a;this.config=b}var d={JSON:{object:"JSON",path:"/json2.js"},jQuery:{object:"BrightTag.jQuery",path:"/BrightTag.jquery-1.5.1.js"}};a.prototype={ensure:function(a,b){var h=d[a];if(h){var e=h.object.split("."),f=window,m=e.length-
1,k,g;for(g=0;g<m;g++){k=e[g];f=f[k];if(!f)throw"DependencyManager: Could not find key "+k;f=f[e[g]]}f?b():this.tagMgrRouter.script(E(this.config.staticHost+h.path)).wait(b)}}};return a}(),N={},G,I=ba(document);try{window.localStorage&&window.sessionStorage&&(G=ca(sessionStorage,localStorage),G.purge())}catch(Oa){bt_log("Unable to access DOM storage: "+Oa)}k.Escaper={cookie:V,javascript:function(a){return!p.isString(a)?a:a.replace(/\\/g,"\\\\").replace(/'/g,"\\x27").replace(/"/g,"\\x22").replace(/\n/g,
"\\n").replace(/\r/g,"\\r")}};k.Random={integer:function(a){return Math.floor(Math.random()*(a||1E8))}};k.pushIfDefined=function(a,d,c){a&&(a.constructor==Array&&null!=d)&&a.push(c||d)};k.ServerURL=ga;k.Main=function(a){function d(b){(b=b.fragment())&&r((new M(b)).params(),function(b,c){a[b]=c[0]})}function c(b){function c(a){bt_log("configuration error: "+a)}b=u(b);0!==b.length&&s(a,z("(\n"+b+"\n)",c,"site-config"))}var b,h,e=function(){var b,c,d=/\/tag(\-\d+\.\d+\.\d+|\.[^.]+|-n)?\.js(#.*)?$/,e=
a.document.getElementsByTagName("script");for(b=e.length-1;-1<b;b--)if(c=e[b],d.test(c.src))return c}();e&&(h=new E(e.src),a.host=a.host||Q(h.host),d(h),c(e.innerHTML));if(null!=a.site){k.Events.enablePageReadyOverrides();try{b=new ia(a,e),k.Events.onDOMReady(b.domReady),b.loadOnly||b.primary()}catch(f){bt_log("execution error: "+f)}return b}};k.CookieSync={pushImage:function(a){(new Image).src=a;throw"CookieSync.pushImage no longer supported ["+a+"]";},pushIframe:function(a){throw"CookieSync.pushIframe no longer supported ["+
a+"]";}};k.EventBindingManager=ha;k.defaultConfig=oa;k.eval=z;k.Types=p;k.trim=x.trim;k.Util=x;k.each=x.each;k.extend=x.extend;k.HTTP={Cookie:S,QueryString:M,URL:E};k.Blab=new aa(document);k.Events=new function(a,d){function c(){}function b(a,b,c){a[s](t+b,c,!1)}function h(a,b,c){a[u](t+b,c,!1)}function e(){var a=d.readyState;if("loading"==a)return!1;if("complete"==a)return!0;a:{try{x("left")}catch(b){a=!1;break a}a=!0}return a}function f(a,b,c){var d=this;setTimeout(function(){a()?b.call(d):f(a,
b,c)},c)}function k(){k=c;n&&da(d,p,d)}function l(){k();da(a,r,d)}var g=this,n=!!a.addEventListener,p="DOMContentLoaded",r="load",s=n?"addEventListener":"attachEvent",u=n?"removeEventListener":"detachEvent",t=n?"":"on",x=d.documentElement.doScroll||function(){throw"No doScroll";};g.listen=b;g.unlisten=h;g.onDOMReady=function(c){e()?c.call(this):d.addEventListener?(b(d,p,c),b(d,p,function(){h(a,r,c)}),b(a,r,c)):f(e,c,1)};g.enablePageReadyOverrides=function(){g.enablePageReadyOverrides=c;e()?l():(n&&
b(d,p,k),b(a,r,l))}}(window,document);k.Events.enablePageReadyOverrides();k.Content=new function(a){a=a||k.Blab;return{iframe:a.iframe,image:a.image,link:a.link,script:a.script}}(k.Blab);k.V2_RESPONSE=!0;k.site=function(a,d){try{var c=N[a];c&&d&&d(c);return c}catch(b){bt_log("error while executing site configuration ["+a+"]: "+b)}};k.configureNewSites=function(a,d){r(La(a.document.getElementsByTagName("script")),function(c){c=Ea(c);c.isTagjs()&&ma(c,a,d)})};k.configureSite=function(a,d,c){return ma(Fa(a),
d,c)};k.configuredSites=function(){var a=[];x.each(N,function(d,c){a.push(c)});return a};k.initializeSite=function(a,d){d&&(k.Events.onDOMReady(d.domReady),d.loadOnly||d.primary());a&&Ma(a)};return k}(window.BrightTag);(function(k){k.configureNewSites(window,k.initializeSite);null==k.instance&&setTimeout(function(){null==k.instance&&k.configureNewSites(window,k.initializeSite)},0)})(BrightTag);var _bt_url_prefix,_bt_referrer,_bt_site,_bt_mode;
function btServe(k){var n=BrightTag,u={referrer:_bt_referrer,site:_bt_site,mode:_bt_mode};null!=_bt_url_prefix&&(u.host=_bt_url_prefix);n.configureSite(n.extend(u,k),window,n.initializeSite)};
